/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorConsultationRouteImport } from './routes/doctor.consultation'
import { Route as DoctorPatientRouteImport } from './routes/doctor.patient'
import { Route as EmergencyIndexRouteImport } from './routes/emergency.index'
import { Route as EmergencyLogRouteImport } from './routes/emergency.log'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientDocumentsRouteImport } from './routes/patient.documents'
import { Route as PatientEmergencyProfileRouteImport } from './routes/patient.emergency-profile'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientQuestionnaireRouteImport } from './routes/patient.questionnaire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationRoute = DoctorConsultationRouteImport.update({
  id: '/doctor/consultation',
  path: '/doctor/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientRoute = DoctorPatientRouteImport.update({
  id: '/doctor/patient',
  path: '/doctor/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyIndexRoute = EmergencyIndexRouteImport.update({
  id: '/emergency/',
  path: '/emergency/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyLogRoute = EmergencyLogRouteImport.update({
  id: '/emergency/log',
  path: '/emergency/log',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDocumentsRoute = PatientDocumentsRouteImport.update({
  id: '/patient/documents',
  path: '/patient/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientEmergencyProfileRoute = PatientEmergencyProfileRouteImport.update({
  id: '/patient/emergency-profile',
  path: '/patient/emergency-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/patient/history',
  path: '/patient/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientQuestionnaireRoute = PatientQuestionnaireRouteImport.update({
  id: '/patient/questionnaire',
  path: '/patient/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/consent': typeof ConsentRoute
  '/offline': typeof OfflineRoute
  '/scenarios': typeof ScenariosRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/emergency/log': typeof EmergencyLogRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/emergency-profile': typeof PatientEmergencyProfileRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/questionnaire': typeof PatientQuestionnaireRoute
  '/doctor/': typeof DoctorIndexRoute
  '/emergency/': typeof EmergencyIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/consent': typeof ConsentRoute
  '/offline': typeof OfflineRoute
  '/scenarios': typeof ScenariosRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/emergency/log': typeof EmergencyLogRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/emergency-profile': typeof PatientEmergencyProfileRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/questionnaire': typeof PatientQuestionnaireRoute
  '/doctor': typeof DoctorIndexRoute
  '/emergency': typeof EmergencyIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/consent': typeof ConsentRoute
  '/offline': typeof OfflineRoute
  '/scenarios': typeof ScenariosRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/emergency/log': typeof EmergencyLogRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/emergency-profile': typeof PatientEmergencyProfileRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/questionnaire': typeof PatientQuestionnaireRoute
  '/doctor/': typeof DoctorIndexRoute
  '/emergency/': typeof EmergencyIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/consent'
    | '/offline'
    | '/scenarios'
    | '/doctor/consultation'
    | '/doctor/patient'
    | '/emergency/log'
    | '/patient/documents'
    | '/patient/emergency-profile'
    | '/patient/history'
    | '/patient/questionnaire'
    | '/doctor/'
    | '/emergency/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/consent'
    | '/offline'
    | '/scenarios'
    | '/doctor/consultation'
    | '/doctor/patient'
    | '/emergency/log'
    | '/patient/documents'
    | '/patient/emergency-profile'
    | '/patient/history'
    | '/patient/questionnaire'
    | '/doctor'
    | '/emergency'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/consent'
    | '/offline'
    | '/scenarios'
    | '/doctor/consultation'
    | '/doctor/patient'
    | '/emergency/log'
    | '/patient/documents'
    | '/patient/emergency-profile'
    | '/patient/history'
    | '/patient/questionnaire'
    | '/doctor/'
    | '/emergency/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ConsentRoute: typeof ConsentRoute
  OfflineRoute: typeof OfflineRoute
  ScenariosRoute: typeof ScenariosRoute
  DoctorConsultationRoute: typeof DoctorConsultationRoute
  DoctorPatientRoute: typeof DoctorPatientRoute
  EmergencyLogRoute: typeof EmergencyLogRoute
  PatientDocumentsRoute: typeof PatientDocumentsRoute
  PatientEmergencyProfileRoute: typeof PatientEmergencyProfileRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientQuestionnaireRoute: typeof PatientQuestionnaireRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  EmergencyIndexRoute: typeof EmergencyIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultation': {
      id: '/doctor/consultation'
      path: '/doctor/consultation'
      fullPath: '/doctor/consultation'
      preLoaderRoute: typeof DoctorConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patient': {
      id: '/doctor/patient'
      path: '/doctor/patient'
      fullPath: '/doctor/patient'
      preLoaderRoute: typeof DoctorPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/': {
      id: '/emergency/'
      path: '/emergency'
      fullPath: '/emergency/'
      preLoaderRoute: typeof EmergencyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/log': {
      id: '/emergency/log'
      path: '/emergency/log'
      fullPath: '/emergency/log'
      preLoaderRoute: typeof EmergencyLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/documents': {
      id: '/patient/documents'
      path: '/patient/documents'
      fullPath: '/patient/documents'
      preLoaderRoute: typeof PatientDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/emergency-profile': {
      id: '/patient/emergency-profile'
      path: '/patient/emergency-profile'
      fullPath: '/patient/emergency-profile'
      preLoaderRoute: typeof PatientEmergencyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/patient/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/questionnaire': {
      id: '/patient/questionnaire'
      path: '/patient/questionnaire'
      fullPath: '/patient/questionnaire'
      preLoaderRoute: typeof PatientQuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ConsentRoute: ConsentRoute,
  OfflineRoute: OfflineRoute,
  ScenariosRoute: ScenariosRoute,
  DoctorConsultationRoute: DoctorConsultationRoute,
  DoctorPatientRoute: DoctorPatientRoute,
  EmergencyLogRoute: EmergencyLogRoute,
  PatientDocumentsRoute: PatientDocumentsRoute,
  PatientEmergencyProfileRoute: PatientEmergencyProfileRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientQuestionnaireRoute: PatientQuestionnaireRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  EmergencyIndexRoute: EmergencyIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
