/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as DoctorConsultationRouteImport } from './routes/doctor.consultation'
import { Route as DoctorPatientRouteImport } from './routes/doctor.patient'
import { Route as EmergencyLogRouteImport } from './routes/emergency.log'
import { Route as PatientDocumentsRouteImport } from './routes/patient.documents'
import { Route as PatientEmergencyProfileRouteImport } from './routes/patient.emergency-profile'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientQuestionnaireRouteImport } from './routes/patient.questionnaire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationRoute = DoctorConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientRoute = DoctorPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => DoctorRoute,
} as any)
const EmergencyLogRoute = EmergencyLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => EmergencyRoute,
} as any)
const PatientDocumentsRoute = PatientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PatientRoute,
} as any)
const PatientEmergencyProfileRoute = PatientEmergencyProfileRouteImport.update({
  id: '/emergency-profile',
  path: '/emergency-profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRoute,
} as any)
const PatientQuestionnaireRoute = PatientQuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/consent': typeof ConsentRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/emergency': typeof EmergencyRouteWithChildren
  '/offline': typeof OfflineRoute
  '/patient': typeof PatientRouteWithChildren
  '/scenarios': typeof ScenariosRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/emergency/log': typeof EmergencyLogRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/emergency-profile': typeof PatientEmergencyProfileRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/questionnaire': typeof PatientQuestionnaireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/consent': typeof ConsentRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/emergency': typeof EmergencyRouteWithChildren
  '/offline': typeof OfflineRoute
  '/patient': typeof PatientRouteWithChildren
  '/scenarios': typeof ScenariosRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/emergency/log': typeof EmergencyLogRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/emergency-profile': typeof PatientEmergencyProfileRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/questionnaire': typeof PatientQuestionnaireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/consent': typeof ConsentRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/emergency': typeof EmergencyRouteWithChildren
  '/offline': typeof OfflineRoute
  '/patient': typeof PatientRouteWithChildren
  '/scenarios': typeof ScenariosRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/emergency/log': typeof EmergencyLogRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/emergency-profile': typeof PatientEmergencyProfileRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/questionnaire': typeof PatientQuestionnaireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/consent'
    | '/doctor'
    | '/emergency'
    | '/offline'
    | '/patient'
    | '/scenarios'
    | '/doctor/consultation'
    | '/doctor/patient'
    | '/emergency/log'
    | '/patient/documents'
    | '/patient/emergency-profile'
    | '/patient/history'
    | '/patient/questionnaire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/consent'
    | '/doctor'
    | '/emergency'
    | '/offline'
    | '/patient'
    | '/scenarios'
    | '/doctor/consultation'
    | '/doctor/patient'
    | '/emergency/log'
    | '/patient/documents'
    | '/patient/emergency-profile'
    | '/patient/history'
    | '/patient/questionnaire'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/consent'
    | '/doctor'
    | '/emergency'
    | '/offline'
    | '/patient'
    | '/scenarios'
    | '/doctor/consultation'
    | '/doctor/patient'
    | '/emergency/log'
    | '/patient/documents'
    | '/patient/emergency-profile'
    | '/patient/history'
    | '/patient/questionnaire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ConsentRoute: typeof ConsentRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  EmergencyRoute: typeof EmergencyRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  PatientRoute: typeof PatientRouteWithChildren
  ScenariosRoute: typeof ScenariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultation': {
      id: '/doctor/consultation'
      path: '/consultation'
      fullPath: '/doctor/consultation'
      preLoaderRoute: typeof DoctorConsultationRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patient': {
      id: '/doctor/patient'
      path: '/patient'
      fullPath: '/doctor/patient'
      preLoaderRoute: typeof DoctorPatientRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/emergency/log': {
      id: '/emergency/log'
      path: '/log'
      fullPath: '/emergency/log'
      preLoaderRoute: typeof EmergencyLogRouteImport
      parentRoute: typeof EmergencyRoute
    }
    '/patient/documents': {
      id: '/patient/documents'
      path: '/documents'
      fullPath: '/patient/documents'
      preLoaderRoute: typeof PatientDocumentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/emergency-profile': {
      id: '/patient/emergency-profile'
      path: '/emergency-profile'
      fullPath: '/patient/emergency-profile'
      preLoaderRoute: typeof PatientEmergencyProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/questionnaire': {
      id: '/patient/questionnaire'
      path: '/questionnaire'
      fullPath: '/patient/questionnaire'
      preLoaderRoute: typeof PatientQuestionnaireRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface DoctorRouteChildren {
  DoctorConsultationRoute: typeof DoctorConsultationRoute
  DoctorPatientRoute: typeof DoctorPatientRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorConsultationRoute: DoctorConsultationRoute,
  DoctorPatientRoute: DoctorPatientRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface EmergencyRouteChildren {
  EmergencyLogRoute: typeof EmergencyLogRoute
}

const EmergencyRouteChildren: EmergencyRouteChildren = {
  EmergencyLogRoute: EmergencyLogRoute,
}

const EmergencyRouteWithChildren = EmergencyRoute._addFileChildren(
  EmergencyRouteChildren,
)

interface PatientRouteChildren {
  PatientDocumentsRoute: typeof PatientDocumentsRoute
  PatientEmergencyProfileRoute: typeof PatientEmergencyProfileRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientQuestionnaireRoute: typeof PatientQuestionnaireRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientDocumentsRoute: PatientDocumentsRoute,
  PatientEmergencyProfileRoute: PatientEmergencyProfileRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientQuestionnaireRoute: PatientQuestionnaireRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ConsentRoute: ConsentRoute,
  DoctorRoute: DoctorRouteWithChildren,
  EmergencyRoute: EmergencyRouteWithChildren,
  OfflineRoute: OfflineRoute,
  PatientRoute: PatientRouteWithChildren,
  ScenariosRoute: ScenariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
